### PR TITLE
Fixes for inlay hint

### PR DESCRIPTION
**Pull request by tcx4c70**

### CODE REVIEW

**Comment by tcx4c70** [comment]
Because of the GFW of China, some screenshots can't be upload.

I was testing with the following example code:
```
class Program
{
    static void Main()
    {
        var list = new [] { "a", "b" };
        var (x, y) = (0, "abc");
    }
}
```

**Comment by razzmatazz** [comment]
LGTM!

**Comment by razzmatazz** [comment]
@tcx4c70 I was wondering if it is possible to somehow remove typehints for assignments where right side already has type name mentioned, e.g. now we get this:

> Bildschirm­foto 2023-03-18 um 16 05 32

so I was thinking if we can do some heuristics that:
- (a) avoid type hints for "var v = new XXX()" assignments
- (b) avoid type hints for "var v = expression<XXX>()" assignments

from looking at both cases above, maybe we can generalize and avoid type hints if expression on the right side already contains type name?

sorry -- maybe I should create a new issue here, but still

**Comment by razzmatazz** [comment]
I can take a look and change your code regarding inlay hints, if you agree that this warrants fixing

**Comment by razzmatazz** [comment]
we are also missing tests, which could help us greatly :(

**Comment by tcx4c70** [comment]
> @tcx4c70 I was wondering if it is possible to somehow remove typehints for assignments where right side already has type name mentioned, e.g. now we get this:
> 
> > Bildschirm­foto 2023-03-18 um 16 05 32
> 
> so I was thinking if we can do some heuristics that:
> 
> * (a) avoid type hints for "var v = new XXX()" assignments
> * (b) avoid type hints for "var v = expression()" assignments
> 
> from looking at both cases above, maybe we can generalize and avoid type hints if expression on the right side already contains type name?

@razzmatazz Sorry that I missed your reply. I also notice the duplicate type hints you mentioned, but i was busy on my work for last month and have no time to improve it. Maybe I'll investigate and imrove it on the next holiday on May.

**Comment by tcx4c70** [comment]
> we are also missing test infrastructure, which could help us greatly :(

Yes, I struggled on testing during my development. Maybe we can add test infrastructure to roadmap or TODO list?

**Comment by razzmatazz** [comment]
> > we are also missing test infrastructure, which could help us greatly :(
> 
> 
> 
> Yes, I struggled on testing during my development. Maybe we can add test infrastructure to roadmap or TODO list?

I was thinking if we can steal that (or most of the bits) from ionide.fsautocomplete

lately i'm a little bit too busy but it should be possible le to produce something copying in the files and doing some rough hacking

**Comment by razzmatazz** [comment]
i'm also not sure how they (fsautocomplete) do the testing, in-proc or out of process --the later feels better for me

**Pull request merged**
