### PR TITLE
dotnet 8 changes in project files and github workflow files

### PR DESCRIPTION
**Pull request by BeauCranston**
Based changes off of the dotnet 7 upgrade. Ran the test project and all 16 tests passed.

### CODE REVIEW

**Comment by Decodetalkers** [comment]
if it is possible to make it both can both used on dotnet 7 and dotnet 8? I don't think godot will switch to dotnet 8 immediately..

**Comment by razzmatazz** [comment]
I am somewhat curious if changing platform/runtime for language server intake would change which dotnet version it supports for client projects m, as roslyn dependencies itself did not change with this PR.

Maybe we need to set some option or something...

**Comment by kstatz12** [comment]
We should probably update the roslyn packages while we are at it here. I can open a seperate PR if that is cleaner?

**Comment by Zedo9** [comment]
> Maybe a configuration option needs to be created that would allow users to change the target framework of the LSP and default to whatever is highest / whatever is set in a global.json above the nvim directory? Not sure if that would break stuff though.

Shouldn't this be determined based on the target defined in `.csproj`? Why would we need to set it manually?

**Comment by kstatz12** [comment]
> We should probably update the roslyn packages while we are at it here. I can open a seperate PR if that is cleaner?

I have a branch doing this. its a load of work since Ionide has breaking changes and theres a version mismatch of some core MS lib if we dont upgrade everything. I dont have enough beer in the fridge this week for that but ill keep chipping away at it

**Comment by razzmatazz** [comment]
This looks good to me! Sorry for the delay

**Comment by razzmatazz** [comment]
> Based changes off of the dotnet 7 upgrade. Ran the test project and all 16 tests passed.

Btw, the tests that we have at the moment are REALLY shallow and do not test functionality that much :(

**Pull request merged**
