### PR TITLE
Integrate refactoring changes (pt. I)

### PR DESCRIPTION
**Pull request by razzmatazz**
PR for gradual integration of https://github.com/razzmatazz/csharp-language-server/pull/102 by @tcx4c70 

CC @tcx4c70 – I am planning to keep this as close as on your PR–ideally getting it to the same state of your tree as you have on your PR but with a gradual cherry-picking of https://github.com/razzmatazz/csharp-language-server/pull/102/commits/9bef099dd23ba83201788d24ce8f0e567bd09b94 (the biggest commit, I recon)

I am also not keen on introducing multiple projects (at least yet) -- like one for Handlers -- but rather add a folder. If you insist I will revert on this but for now that seemed to be excessive.

### CODE REVIEW

**Comment by rudiejd** [comment]
this is an awesome change for code quality! everything looks good to me. I'll try running this version for a couple of days

**Comment by tcx4c70** [comment]
Thanks @razzmatazz, I'll close my original PR.

**Comment by razzmatazz** [comment]
> Thanks @razzmatazz, I'll close my original PR.

Please don't do that yet–this PR will be impartial (mostly file renames/shuffling things around to match your tree).
I plan for the actual contentful changes to be merge in subsequent PRs.
Also that PR provides grounds for discussion.

**Comment by razzmatazz** [comment]
> this is an awesome change for code quality! everything looks good to me. I'll try running this version for a couple of days

Oh, this PR is just for shuffling code around to match the @tcx4c70 tree as closely as possible to further cherry-picks can be applied more easily. There should be NO behaviour change after merging this one.

**Pull request merged**
